### ISSUE TITLE
Rejected by Elasticsearch [error type]: mapper_parsing_exception [reason]: 'object mapping for [kubernetes.labels.app] tried to parse field [app] as object, but found a concrete value

### ISSUE THREAD

**Issue by tirelibirefe** [uken/fluent-plugin-elasticsearch#787]
(check apply)
- [ok ] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

I would like to forward kubernetes logs from fluent-bit to fluentd and  from fluentd to elasticsearch. fluentbit forwards logs to fluentd but fluentd cannot fix parsing errors.
fluent-bit cannot parse kuberntes logs properly.

#### Steps to replicate
there is nothing special; out of box stable/fluentbit or fluent/fluent-bit helm chart installation and stable/fluentd installation.

`Rejected by Elasticsearch [error type]: mapper_parsing_exception [reason]: 'object mapping for [kubernetes.labels.app] tried to parse field [app] as object, but found a concrete value`

**OR**

Provide example config and message

#### Expected Behavior or What you need to ask

I expect fluentbit can be used to read and parse Kubernetes logs properly.

#### Using Fluentd and ES plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* Fluentd v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``

`Rejected by Elasticsearch [error type]: mapper_parsing_exception [reason]: 'object mapping for [kubernetes.labels.app] tried to parse field [app] as object, but found a concrete value
`
* ES plugin 3.x.y/2.x.y or 1.x.y >> no idea. I didn't install anything extra.
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
there is no gemfile in helm charts stable/fluentbit fluent/fluentbit. If there is, I don't know to check it.

* ES version (optional) 7.8
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
This should be Elasticsearchmapping issue not fluentd ES plugin.

**Comment by cosmo0920** [comment]
And no fluentd configuration cannot be reproducible this issue. Thanks!!!

**Comment by cosmo0920** [comment]
https://github.com/uken/fluent-plugin-elasticsearch#random-400---rejected-by-elasticsearch-is-occured-why might solve this issue?

**Comment by tirelibirefe** [comment]
> https://github.com/uken/fluent-plugin-elasticsearch#random-400---rejected-by-elasticsearch-is-occured-why might solve this issue?

I know you're not helm chart maintainer but I have to say....
I use "helm charts" to deploy applications. Wish the documentation was prepared suitable to helm charts and Kubernetes environment.

**Comment by cosmo0920** [comment]
> Wish the documentation was prepared suitable to helm charts and Kubernetes environment.

I dislike to prepare documentation which is for not maintainer using helm chart. This causes unnecessary confusions.
We cannot help about it. Thanks.

**Comment by cosmo0920** [comment]
This issue should be reported on helm chart repository.

**Comment by simonasr** [comment]
This is a common problem with k8s labels which can contain dots in their names.
Usually this is solved by replacing dots with underscores:
* Fluent-bit does this with `Replace_Dots` feature in elasticsearch output plugin. https://github.com/fluent/fluent-bit/commit/6764ac7d9aa500cba3b51f835b64fd4cb7bea14b
* Filebead does this with `labels.dedot` feature. https://github.com/elastic/beats/commit/d5bda769e4eed723fe79d1209959ae15e8c691b4

It would be great, if `fluent-plugin-elasticsearch` plugin has this feature.
@cosmo0920

**Comment by cosmo0920** [comment]
Please use dedot plugin.
https://github.com/lunardial/fluent-plugin-dedot_filter
I hate monolithic plugin.
Thanks!!!

**Comment by jfcmartins** [comment]
Hey @tirelibirefe :wave: did you managed to fix this issue? I tried to use the plugin dedot filter but the warning still appears on my side :thinking_face:

**Comment by shikharagarwal19** [comment]
Hi, 

I was facing the same issue, I used lua filter to resolve this issue for `kubernetes.labels.app` parse error, one can find my solution 
[here](https://github.com/fluent/fluent-bit/issues/4386#issuecomment-1594660386)

**Comment by jingzhao-self** [comment]
found fluent-plugin-elasticsearch (5.1.5) is ok, but fluent-plugin-elasticsearch (5.2.5) has the similar random problem, please some guy have a try to check this.
